# src/ingestion/who_ghe_factory.py

import requests
import pandas as pd
from pathlib import Path

HEADERS = {
    "User-Agent": "EDA-MLOps-Portfolio",
    "Accept": "application/json"
}

# EXACT URLs generated by WHO UI (LOCKED)
WHO_GHE_URLS = {
    2000: "https://xmart-api-public.who.int/DEX_CMS/GHE_FULL?$filter=FLAG_RANKABLE%20eq%201%20and%20DIM_COUNTRY_CODE%20eq%20%27IND%27%20and%20DIM_SEX_CODE%20eq%20%27MALE%27%20and%20DIM_AGEGROUP_CODE%20eq%20%27TOTAL%27%20and%20DIM_YEAR_CODE%20eq%202000&$orderBy=VAL_DALY_RATE100K_NUMERIC%20desc&$select=DIM_GHECAUSE_CODE,DIM_GHECAUSE_TITLE,VAL_DALY_RATE100K_NUMERIC,VAL_DTHS_RATE100K_NUMERIC&$top=10",
    2010: "https://xmart-api-public.who.int/DEX_CMS/GHE_FULL?$filter=FLAG_RANKABLE%20eq%201%20and%20DIM_COUNTRY_CODE%20eq%20%27IND%27%20and%20DIM_SEX_CODE%20eq%20%27MALE%27%20and%20DIM_AGEGROUP_CODE%20eq%20%27TOTAL%27%20and%20DIM_YEAR_CODE%20eq%202010&$orderBy=VAL_DALY_RATE100K_NUMERIC%20desc&$select=DIM_GHECAUSE_CODE,DIM_GHECAUSE_TITLE,VAL_DALY_RATE100K_NUMERIC,VAL_DTHS_RATE100K_NUMERIC&$top=10",
    2021: "https://xmart-api-public.who.int/DEX_CMS/GHE_FULL?$filter=FLAG_RANKABLE%20eq%201%20and%20DIM_COUNTRY_CODE%20eq%20%27IND%27%20and%20DIM_SEX_CODE%20eq%20%27MALE%27%20and%20DIM_AGEGROUP_CODE%20eq%20%27TOTAL%27%20and%20DIM_YEAR_CODE%20eq%202021&$orderBy=VAL_DALY_RATE100K_NUMERIC%20desc&$select=DIM_GHECAUSE_CODE,DIM_GHECAUSE_TITLE,VAL_DALY_RATE100K_NUMERIC,VAL_DTHS_RATE100K_NUMERIC&$top=10"
}


def fetch_who_ghe_year(year: int) -> pd.DataFrame:
    """
    Fetch WHO GHE Top-10 DALY causes for India for a given year
    using UI-generated OData URL.
    """
    url = WHO_GHE_URLS[year]
    response = requests.get(url, headers=HEADERS, timeout=60)
    response.raise_for_status()

    df = pd.DataFrame(response.json()["value"])
    df["year"] = year

    return df


def save_who_ghe_raw(years: list[int]) -> None:
    """
    Save raw WHO GHE DALY datasets to datasets/raw/health/
    """
    raw_dir = Path("datasets/raw/health")
    raw_dir.mkdir(parents=True, exist_ok=True)

    for year in years:
        df = fetch_who_ghe_year(year)
        out_path = raw_dir / f"ghe_dalys_india_{year}.csv"
        df.to_csv(out_path, index=False)
